// Auto-generated by prebuild.mjs - DO NOT EDIT
// This file contains a hash of the parser implementations at build time.
// It's used for automatic cache invalidation when parser code changes.
export const BUILD_TIME_PARSER_SIGNATURE = '1aea9423905783c619b84d7d287214f1bfa6de672718cd642a0e485b6af54340';
