#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const packageJsonPath = join(__dirname, 'package.json');
const versionTsPath = join(__dirname, 'src', 'version.ts');

const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version || '0.0.0';

const content = `// Auto-generated by prebuild.mjs - do not edit manually
export const packageVersion = '${version}';
`;

writeFileSync(versionTsPath, content, 'utf8');
console.log(`Generated ${versionTsPath} with version ${version}`);